### ISSUE TITLE
Multiple terrains do not work

### ISSUE THREAD

**Issue by ape97** [MCrafterzz/lowpolyterraineditor#2]
**First of all, a very very cool and super project.** 

Unfortunately, it is not possible to create a second terrain, because if I do that and change the position, I can no longer edit the terrain.

We would like to create different terrains and put them together later.

It would be very cool if you build in that you can enlarge the terrain without everything being reset, so for example enlarge to the left or bottom.Another idea would be that you allow to have multiple terrains and allow them to be painted at the same time, so that you can make transitions between terrains.

Thanks for your work so far.

**Comment by MarcusElg** [comment]
It has been over 2 years since I updated this lol :P I remember it being quite slow so it would defiantly need some compute shaders. The code is open source so you can continue working on it if you want
